name: almacen_android
description: Aplicación Android para Canal 12 por Mindia

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.0
  equatable: ^2.0.0
  http: ^0.12.2
  flutter_easyloading: ^3.0.0
  cupertino_icons: ^1.0.1
  qrscan: ^0.3.1
  permission_handler:


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
